# Generated by Django 5.0.2 on 2024-02-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=30)),
                ('book_id', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
                ('year_of_publishing', models.DateField()),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
